### ISSUE TITLE
Defaulting to dark mode.

### ISSUE THREAD

**Issue by ghost** [rileyjshaw/dark-theme-everywhere#1]
The theme default to "dark mode always" only works when the settings page for the extension is opened (i.e. I have to keep the "options" tab always open in order to automatically get dark pages). I am currently using the Chrome 49 dev branch.   

Thanks for the great extension!

**Comment by rileyjshaw** [comment]
Hmm–strange! Thanks for letting me know.

I can't reproduce on my own machine (stable channel), but maybe we can debug the problem remotely.
- Are you using the extension in an incognito tab?
- Which operating system are you on?
- If you open the Console (Mac: `Cmd` + `Option` + `J`, Windows: `Ctrl` + `Shift` + `J`), does it show any errors?

Thanks again :) :) hope we can figure this out!

**Comment by rileyjshaw** [comment]
Found some time to look into this, I think I caught the bug. Let me know if it persists over the next few days @allanjmart :+1:
