### ISSUE TITLE
Darkening Media as well

### ISSUE THREAD

**Issue by MentalGear** [rileyjshaw/dark-theme-everywhere#4]
Hi there,
Great extension and works better than most of the inverters / dimmers one finds on the store.

However, I think media (images, video, embeds) should be darkened as well, as otherwise their brightness still persists and distracts from the content.

I made a simple [example to show the difference](http://jsfiddle.net/qqmw301m/1/embedded/result/) (click any side to enlarge), and with this line of css you can add it to your extension:

```
img, video, embed
        -webkit-filter: brightness(75%) grayscale(15%)
```

comment: updated link

**Comment by rileyjshaw** [comment]
Awesome examples in your link. This seems reasonable to me, I'll add it in :)

**Comment by rileyjshaw** [comment]
Added in [v5.0.0](https://github.com/rileyjshaw/dark-theme-everywhere/commit/7c051d3adaf74a29abd7515af89033f9f04bbefa)!

**Comment by MentalGear** [comment]
👍

**Comment by MentalGear** [comment]
default on ?

**Comment by rileyjshaw** [comment]
Yep! Do you think it would be better to default it to off?

**Comment by MentalGear** [comment]
Nah, on should be default ! :-)
