### ISSUE TITLE
Facebook videos are invisible

### ISSUE THREAD

**Issue by YuyQuan** [rileyjshaw/dark-theme-everywhere#8]

**Comment by rileyjshaw** [comment]
I can't seem to reproduce - do you have a link that I can test on?

**Comment by MentalGear** [comment]
works fine for me too.

**Comment by rileyjshaw** [comment]
@MentalGear thanks for looking! I'm going to close this for now, @YuyQuan let me know if you have any additional info.

**Comment by MentalGear** [comment]
Well, what's true for me is that there's like a second delay until videos show up. But they always show up.

**Comment by YuyQuan** [comment]
I thought I left a reply. I meant to clarify: 360 videos are invisible. Here is a 360 video: https://www.facebook.com/UnrealityJourneys/videos/612648205581682/
